spring.application.name=gateway

server.port = 8888

management.endpoints.web.exposure.include=*




logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway=TRACE

#Eureka confirguration URL 
#spring.cloud.gateway.mvc.routes[0].id=user-service
#spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8001
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/user/**

#spring.cloud.gateway.mvc.routes[1].id=product-service0
#spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8010
#spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/product/**

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#Config server URL :
spring.config.import=optional:configserver:http://localhost:9988/config